sections:
  product_details:
    type: arcade-product-details
    blocks:
      title:
        type: title
      price:
        type: price
      stock:
        type: stock
      short_description:
        type: short_description
      quantity_selector:
        type: quantity_selector
      buy_buttons:
        type: buy_buttons
      description:
        type: description
      attributes:
        type: attributes

    blocks_order:
      - title
      - price
      - stock
      - short_description
      - quantity_selector
      - buy_buttons
      - description
      - attributes

# sections order
order:
  - product_details
